"""initial trading schema

Creates every table from the SQLAlchemy models.

Why the initial revision is metadata-driven rather than a long list of
``op.create_table`` calls: the models use dialect-aware types
(``JSON`` -> ``JSONB`` on Postgres, ``UTCDateTime``), and an autogenerated script
bakes in whichever dialect happened to be used to generate it. Building the
initial schema from the metadata keeps Postgres and SQLite identical to the
models by construction.

Subsequent revisions SHOULD be autogenerated against a real Postgres instance
and reviewed by hand:

    docker compose up -d postgres
    docker compose run --rm python-trading-service \
        alembic revision --autogenerate -m "describe the change"

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-13
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op

from app.database.models import Base

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    # Destructive by definition: drops every table and all trading history.
    Base.metadata.drop_all(bind=op.get_bind())
