"""Canonical event names used in structured logs and the ``system_events`` table.

Keeping these as constants (rather than ad-hoc strings) means dashboards and
log queries never drift from the code that emits them.
"""

from __future__ import annotations

from enum import StrEnum


class EventType(StrEnum):
    # --- data
    MARKET_UPDATE = "MARKET_UPDATE"
    MARKET_DATA_REJECTED = "MARKET_DATA_REJECTED"
    MARKET_DATA_STALE = "MARKET_DATA_STALE"
    FEATURES_CALCULATED = "FEATURES_CALCULATED"
    REGIME_CLASSIFIED = "REGIME_CLASSIFIED"

    # --- decisioning
    SIGNAL_GENERATED = "SIGNAL_GENERATED"
    NO_SETUP = "NO_SETUP"
    AI_CONTEXT_BUILT = "AI_CONTEXT_BUILT"
    AI_DECISION = "AI_DECISION"
    AI_PARSE_FAILED = "AI_PARSE_FAILED"
    AI_SKIPPED = "AI_SKIPPED"

    # --- risk
    RISK_APPROVED = "RISK_APPROVED"
    RISK_REJECTED = "RISK_REJECTED"
    RISK_APPROVAL_CONSUMED = "RISK_APPROVAL_CONSUMED"
    RISK_APPROVAL_INVALID = "RISK_APPROVAL_INVALID"

    # --- execution
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_REJECTED = "ORDER_REJECTED"
    ORDER_FILLED = "ORDER_FILLED"
    ORDER_PARTIALLY_FILLED = "ORDER_PARTIALLY_FILLED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    ORDER_DUPLICATE_IGNORED = "ORDER_DUPLICATE_IGNORED"
    POSITION_OPENED = "POSITION_OPENED"
    POSITION_UPDATED = "POSITION_UPDATED"
    POSITION_CLOSED = "POSITION_CLOSED"
    STOP_TRIGGERED = "STOP_TRIGGERED"
    TAKE_PROFIT_TRIGGERED = "TAKE_PROFIT_TRIGGERED"
    TRAILING_STOP_MOVED = "TRAILING_STOP_MOVED"
    BREAKEVEN_STOP_MOVED = "BREAKEVEN_STOP_MOVED"
    PARTIAL_EXIT = "PARTIAL_EXIT"

    # --- system / safety
    BOT_STARTED = "BOT_STARTED"
    BOT_HALTED = "BOT_HALTED"
    BOT_RESET = "BOT_RESET"
    KILL_SWITCH_TRIGGERED = "KILL_SWITCH_TRIGGERED"
    EMERGENCY_EVENT = "EMERGENCY_EVENT"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    LIVE_MODE_BLOCKED = "LIVE_MODE_BLOCKED"
    DAILY_REPORT_GENERATED = "DAILY_REPORT_GENERATED"
    BACKTEST_COMPLETED = "BACKTEST_COMPLETED"
    WALKFORWARD_COMPLETED = "WALKFORWARD_COMPLETED"


class HaltReason(StrEnum):
    MAX_DAILY_LOSS = "MAX_DAILY_LOSS"
    MAX_DRAWDOWN = "MAX_DRAWDOWN"
    MARKET_DATA_STALE = "MARKET_DATA_STALE"
    EXCHANGE_FAILURE = "EXCHANGE_FAILURE"
    REPEATED_ORDER_FAILURES = "REPEATED_ORDER_FAILURES"
    DATABASE_FAILURE = "DATABASE_FAILURE"
    ABNORMAL_MARKET_MOVEMENT = "ABNORMAL_MARKET_MOVEMENT"
    MANUAL = "MANUAL"
    WORKFLOW_FAILURE = "WORKFLOW_FAILURE"
